local_enable=YES

write_enable=YES

chroot_local_user=YES

local_root=/var/www/html

allow_writeable_chroot=YES

listen=YES

anonymous_enable=NO

pasv_enable=YES

pasv_min_port=21702
pasv_max_port=21712
